import Head from 'next/head'
import Image from 'next/image'
import React from 'react';
import Favorite from '../Components/Favorite';

const Home = () => {
  return (
    <div>
      <Head>
        <title>Привет, это Дядька в кино!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Favorite />
    </div>
  )
}

export default Home
