import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Hero from '../Components/Hero';

const Home = ({ data }) => {

  return (
    <div>
      <Head>
        <title>Привет, это Дядька в кино!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero data={data.items} />
    </div>
  )
}

export default Home

export async function getServerSideProps(context) {

  const response = await fetch('https://blackend.top/api/video/selection?name=main-slider');
  const data = await response.json();

  return {
    props: {
      data
    }, // will be passed to the page component as props
  }
}